organization model
hack4impact/oacce pull request #1
Opened 2018-02-16 16:21 UTC by OBrandon

2018-02-19 03:11 UTC, riyer15 requested changes

2018-02-19 03:11 UTC, riyer15 commented on app/models/user.py
> +    default = db.Column(db.Boolean, default=False, index=True)
What is this field for?

2018-02-19 03:11 UTC, riyer15 commented on app/models/user.py
> +    permissions = db.Column(db.Integer)
Also, what is this field for?

2018-02-19 03:11 UTC, riyer15 commented on app/models/user.py
> +    tags = db.relationship('Tag', backref='organizations', lazy=True)
Can we make have Disability Programming/Accessibility, Ages (tags), and Services offered each have their own tag-based field? Because this is not a generalized project, we can implement specific fields. We also want to be able to filter over these attributes separately. There's a good example in the RTM project: 
https://github.com/hack4impact/reading-terminal-market/blob/master/app/models/tag.py

The tag model should also be many-to-many, not 1-1 as done here. I'll write more below (see: https://github.com/hack4impact/reading-terminal-market/blob/master/app/models/user.py)

2018-02-19 03:11 UTC, riyer15 commented on app/models/user.py
> +class Tag(db.Model):
In addition to a model for just 1 tag, we should also have an association table between tags and organizations so we can associate many tags with 1 vendor, and many vendors with a tag (see RTM). We also want to have 3 types of tags as i said abovee

2018-02-19 03:11 UTC, riyer15 commented on app/models/user.py
> +    street_number = db.Column(db.Integer)
Maybe we can have the address as 1 string (very long) instead of with all these smaller fields?

2018-02-22 02:30 UTC, OBrandon commented on app/models/user.py
> +    default = db.Column(db.Boolean, default=False, index=True)
That was a mistake. I'll remove the default field.

2018-02-22 02:31 UTC, OBrandon commented on app/models/user.py
> +    permissions = db.Column(db.Integer)
yea I was using another model for reference and forgot to delete those fields.

2018-02-24 05:10 UTC, riyer15 approved these changes

2018-02-24 05:14 UTC, riyer15 commented
Finished up the modification of the organization model. The finalized model has a many-many relationship between Organizations and Tags, and a One-Many relationship between TagType and Tag. The association table associates Organizations and Tags, and the Tag Model integrates a Tag Type parent with it.

2018-02-24 07:36 UTC, abhisuri97 commented
Note I made quite a few changes so we can maintain pep8 style conventions. additionally, there were a few syntax errors/typos that slipped by me earlier, but the good news is that now everything should work fine 👍 

for some reason user.py got renamed to admin_user.py, i changed that back.

2018-02-24 15:47 UTC, merged